---
title: "Instacart Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
instacart_df = 
  instacart %>% 
  sample_n(5000) %>% 
  select(reordered, user_id, order_dow, order_hour_of_day,
         product_name, aisle, department) %>% 
  filter(!department == "missing") %>% 
  mutate(
    order_dow = factor(order_dow, levels = 0:6, labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Order Frequency by Hour of Day and Department
```{r}
hourly_department_counts = instacart_df %>%
  count(order_hour_of_day, department)

plot_ly(hourly_department_counts, x = ~order_hour_of_day, y = ~n, 
        type = "scatter",
        mode = "lines", 
        color = ~department) %>%
  layout(xaxis = list(title = "Hour of the Day",
                      tickvals = 0:23),
         yaxis = list(title = "Number of Orders"))
```
Fresh fruits and vegetables are the most frequently ordered on instacart.

Column {data-width=350}
-----------------------------------------------------------------------

### Order Frequency by Day of Week and Department

```{r}
day_department_counts = instacart_df %>% 
  count(order_dow, department) 

plot_ly(day_department_counts, x = ~order_dow, y = ~department, z = ~n, 
        type = "heatmap", colors = "Blues") %>% 
  layout(
         xaxis = list(title = "Day of the Week"),
         yaxis = list(title = "Department"))
```

### Order Frequency by Department

```{r}
instacart_df %>%
  count(department) %>% 
  mutate(
    department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department,
          type = "bar") %>% 
  layout(
         xaxis = list(title = "Department"),
         yaxis = list(title = "Orders"))
```

