---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---
# interactive plots

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Initial data cleaning

```{r}
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(rating = review_scores_location /2) %>% 
  select(
    rating, neighbourhood_group, neighbourhood,
    room_type, lat, long, price) %>% 
  drop_na(rating) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Use plotly to make plots
scatterplot
```{r}
nyc_airbnb %>% 
  mutate(
    text_lable = str_c("Price:", price, "\nNeighbourhood:", neighbourhood)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_lable,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

box-plot
```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```
bar chart with number of rentals
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  )
```


